(()=>{
  const viewKey="instron-report-view",viewButtons=[...document.querySelectorAll("[data-view-choice]")],
    readingButtons=[...document.querySelectorAll("[data-reading-view]")],gallery=document.querySelector(".graph-gallery"),
    galleryFrame=document.querySelector(".gallery-frame"),chartSelect=document.querySelector("#chart-select"),
    chartCount=document.querySelector("[data-chart-count]"),dialog=document.querySelector(".chart-dialog"),
    dialogFrame=document.querySelector(".dialog-frame"),detailSelect=document.querySelector("#section-jump");
  let reading=document.body.dataset.initialReading||"overview",chartIndex=0,activeCharts=[];
  function compact(){return document.body.dataset.view==="phone"||(document.body.dataset.view==="auto"&&matchMedia("(max-width: 700px)").matches)}
  function setView(view,save){if(!["auto","phone","desktop"].includes(view))view="auto";document.body.dataset.view=view;for(const b of viewButtons)b.setAttribute("aria-pressed",String(b.dataset.viewChoice===view));if(save)try{localStorage.setItem(viewKey,view)}catch{}applyLayout()}
  function applyLayout(){const isCompact=compact();document.body.dataset.compact=String(isCompact);document.body.dataset.reading=reading;for(const b of readingButtons)b.setAttribute("aria-selected",String(b.dataset.readingView===reading));if(gallery)gallery.hidden=!isCompact||!["graphs","training"].includes(reading);if(detailSelect)detailSelect.parentElement.hidden=!isCompact||reading!=="details";if(isCompact&&["graphs","training"].includes(reading)){activeCharts=charts.filter(c=>reading==="training"?c.kind==="training":c.kind!=="training");chartIndex=0;populateChartSelect();displayChart(0)}}
  function setReading(next){if(["overview","motion","graphs","training","details"].includes(next)){reading=next;applyLayout();if(compact())window.scrollTo({top:0,behavior:"smooth"})}}
  let initial="auto";try{initial=new URLSearchParams(location.search).get("view")||localStorage.getItem(viewKey)||initial}catch{}document.body.dataset.view=initial;for(const b of viewButtons)b.addEventListener("click",()=>setView(b.dataset.viewChoice,true));for(const b of readingButtons)b.addEventListener("click",()=>setReading(b.dataset.readingView));
  const reportSections=[...document.querySelectorAll(".report-section")];for(const section of reportSections){const heading=section.querySelector("h2");if(!heading||section.classList.contains("motion-viewer-section"))continue;const option=document.createElement("option");option.value=section.id;option.textContent=heading.textContent.trim();detailSelect?.append(option)}
  detailSelect?.addEventListener("change",()=>{const target=document.getElementById(detailSelect.value);if(target)target.scrollIntoView({behavior:"smooth",block:"start"})});
  for(const root of document.querySelectorAll(".html-content")){
    for(const table of root.querySelectorAll("table")){if(!table.parentElement.classList.contains("scroll-frame")){const wrap=document.createElement("div");wrap.className="scroll-frame";table.before(wrap);wrap.append(table)}for(const cell of table.querySelectorAll("td")){const value=cell.textContent.trim();if(/^[+-]?(?:\d[\d,]*(?:\.\d+)?|\.\d+)(?:e[+-]?\d+)?\s*(?:%|°?[a-zA-Zµμ/·^0-9-]+)?$/i.test(value))cell.classList.add("numeric")}}
    for(const svg of root.querySelectorAll("svg")){if(!svg.hasAttribute("viewBox")){const w=parseFloat(svg.getAttribute("width")),h=parseFloat(svg.getAttribute("height"));if(w&&h)svg.setAttribute("viewBox",`0 0 ${w} ${h}`)}svg.setAttribute("preserveAspectRatio",svg.getAttribute("preserveAspectRatio")||"xMidYMid meet");if(!svg.parentElement.classList.contains("chart-scroll")){const wrap=document.createElement("div");wrap.className="scroll-frame chart-scroll";svg.before(wrap);wrap.append(svg)}}
  }
  function nearestTitle(el){const section=el.closest(".report-section")||el.closest(".section")||el.parentElement;const headings=[...(section?.querySelectorAll("h2,h3,h4")||[])];let preceding=headings.filter(h=>{const relation=h.compareDocumentPosition(el);return relation&Node.DOCUMENT_POSITION_FOLLOWING}).pop();if(preceding&&preceding.tagName!=="H2")return preceding.textContent.trim();return headings[0]?.textContent.trim()||"Graph"}
  function uniqueSvgIds(svg,index){const map=new Map();for(const el of [svg,...svg.querySelectorAll("*")])if(el.id){const id=el.id,newId=`gallery-${index}-${id}`;map.set(id,newId);el.id=newId}for(const el of [svg,...svg.querySelectorAll("*")])for(const attr of [...el.attributes]){let value=attr.value;for(const [oldId,newId] of map){value=value.replaceAll(`url(#${oldId})`,`url(#${newId})`);if((attr.name==="href"||attr.name.endsWith(":href"))&&value===`#${oldId}`)value=`#${newId}`}if(value!==attr.value)el.setAttribute(attr.name,value)}}
  let cloneNumber=100000;function chartClone(chart){const node=chart.node.cloneNode(true);for(const svg of node.querySelectorAll("svg"))uniqueSvgIds(svg,cloneNumber++);return node}
  const charts=[];let chartNumber=0;
  for(const section of reportSections){if(section.classList.contains("motion-viewer-section"))continue;const kind=section.dataset.kind||"details";for(const svg of section.querySelectorAll(".html-content svg")){chartNumber++;const title=nearestTitle(svg),node=document.createElement("div");node.className="html-content";const clone=svg.cloneNode(true);uniqueSvgIds(clone,chartNumber);clone.setAttribute("role","img");clone.setAttribute("aria-label",title);node.append(clone);const associated=svg.parentElement.nextElementSibling?.matches(".legendrow,.legend")?svg.parentElement.nextElementSibling:svg.nextElementSibling?.matches(".legendrow,.legend")?svg.nextElementSibling:null;if(associated)node.append(associated.cloneNode(true));charts.push({title,node,kind})}
    for(const img of section.querySelectorAll(".html-content img,figure img")){chartNumber++;const title=nearestTitle(img),figure=img.closest("figure"),node=document.createElement("figure"),clone=img.cloneNode(true);clone.setAttribute("aria-label",title);node.append(clone);const caption=figure?.querySelector("figcaption");if(caption)node.append(caption.cloneNode(true));charts.push({title,node,kind})}}
  function populateChartSelect(){if(!chartSelect)return;chartSelect.replaceChildren();activeCharts.forEach((chart,index)=>{const option=document.createElement("option");option.value=String(index);option.textContent=chart.title;chartSelect.append(option)});const empty=activeCharts.length===0;chartSelect.disabled=empty;document.querySelector("[data-chart-expand]").disabled=empty;document.querySelector("[data-chart-prev]").disabled=empty;document.querySelector("[data-chart-next]").disabled=empty}
  function displayChart(index){if(!activeCharts.length){galleryFrame.textContent=reading==="training"?"No training graphs are included in this report.":"No graphs are included in this report.";chartCount.textContent="";return}chartIndex=(index+activeCharts.length)%activeCharts.length;const chart=activeCharts[chartIndex];galleryFrame.replaceChildren(chartClone(chart));chartCount.textContent=`${chartIndex+1} of ${activeCharts.length} · ${chart.title}`;chartSelect.value=String(chartIndex)}
  activeCharts=charts.filter(c=>reading==="training"?c.kind==="training":c.kind!=="training");populateChartSelect();
  if(gallery)displayChart(0);
  chartSelect?.addEventListener("change",()=>displayChart(Number(chartSelect.value)));document.querySelector("[data-chart-prev]")?.addEventListener("click",()=>displayChart(chartIndex-1));document.querySelector("[data-chart-next]")?.addEventListener("click",()=>displayChart(chartIndex+1));
  document.querySelector("[data-chart-expand]")?.addEventListener("click",()=>{if(!activeCharts.length)return;dialogFrame.replaceChildren(chartClone(activeCharts[chartIndex]));const svg=dialogFrame.querySelector("svg");if(svg){svg.style.width=`${svg.viewBox.baseVal.width||900}px`;svg.style.maxWidth="none";svg.style.maxHeight="none"}dialog.showModal()});document.querySelector("[data-chart-close]")?.addEventListener("click",()=>dialog.close());dialog?.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});document.querySelector("[data-motion-fullscreen]")?.addEventListener("click",()=>document.querySelector(".motion-viewer-section")?.requestFullscreen?.());
  window.addEventListener("resize",applyLayout);window.addEventListener("keydown",event=>{if(event.key==="Escape"&&dialog?.open)dialog.close()});applyLayout();
})();
